### ISSUE TITLE
Clarify behavior of numbers in JCS specification

### ISSUE THREAD

**Issue by tupelo-schneck** [cyberphone/json-canonicalization#3]
The current JCS draft spec has:

    the JSON data MUST be compatible both with ES6 and I-JSON [RFC7493], which implies the following:
    o  Data of the type "Number" MUST be expressible as IEEE-754 [IEEE754] double precision values.

One issue with this is that I-JSON [RFC7493] does not use "MUST" to restrict the space of allowable numbers---arbitrary numbers are valid I-JSON.  Also what "compatible with ES6" means is not clear, since ES6 obviously allows any JSON text, although not all JSON texts will have a content-preserving round trip through `JSON.stringify(JSON.parse(input))`.

Another issue is that the spec itself uses 333333333.33333329 as an example, which is not "expressible as an IEEE-754 double precision value".

So what is the expected behavior of a spec-compliant JCS converter to be?  Should it reject input like 333333333.33333329 or 1e-400 or 1e+400?  Accept the input but behavior is undefined?

My suggestion: accept any valid I-JSON, including arbitrary numbers, and have a well-defined canonical output for any possible input.  For numbers like 333333333.33333329 the spec already apparently intends this.  But examples like 1e-400 and 1e+400 could also be accepted by requiring output compatible with ES6 `JSON.stringify(JSON.parse(input))`.  In particular `1e-400` would be canonicalized as `0`, and `1e+400` would be canonicalized as `null`.  That last example is slightly counterintuitive, but as long as the output is well-defined, the scheme can be used by anyone trying to convert JSON texts into a canonical form for hashing or signing.

Finally, I suggest making the "Note 2" enhancement to Section 7.1.12.1 of ES6 required.  If it is optional, you have a canonicalization scheme where two different implementations are allowed to produce two different canonicalizations of the same legal input, which seems fundamentally wrong.

**Comment by cyberphone** [comment]
Oooh, JSON numbers are killing me 😟

Since JCS is currently based on that numbers when expressed as _JSON Numbers_ fit in IEEE-754 double precision, values outside of that _range_ produces undefined results.  **This should be added to the draft**. 

Regarding values having values that cannot be exactly represented, they are assumed to be rounded according to normal rounding rules.  **This should be added to the draft**.

Dealing with numbers outside of IEEE-754 would make JCS depend on stand-alone parsers which is not the [long-time] goal as discussed in https://github.com/cyberphone/json-canonicalization/issues/2.

Having successfully implemented (ported to be more correct), the horrendously complex "Note 2" scheme in C#, **I guess it could be changed into a MUST**.

**Comment by tupelo-schneck** [comment]
Unfortunately, I don't think "rounded according to the normal rounding rules" is right.

In Chrome:

JSON.stringify(JSON.parse('333333333.33333329'))
"333333333.3333333"
JSON.stringify(JSON.parse('333333333.33333328'))
"333333333.33333325"

That first one looks like "normal rounding" to me but the second one sure doesn't.  And this isn't even about Note 2.

I don't quite understand what you mean about depending on stand-alone parsers.  Plain old ES6 JSON.parse is perfectly happy to accept JSON which includes numbers outside of IEEE-754, although it doesn't necessary preserve their meaning.  My suggestion is that JCS as a specification require dealing with numbers outside of IEEE-754 (in either range or precision) the exact same way as ES6.

**Comment by cyberphone** [comment]
I tried the examples in my four reference implementations and they all gave the same result.  I believe the platforms' built-in double parsers use rounding according to IEEE-754 which probably is a better definition than "normal rounding".

Since JCS is defined to be used in JSON contexts where the JSON Number range is limited to what IEEE-754 double precision offers, it is unnecessary specifying what happens outside of that range.  The reference implementations doesn't deal with such numbers in a uniform way due to dependencies on number parsing performed by the platform itself.  AFAICT, only a _text-level canonicalizer_ completely disconnected from existing number parsers can deal with arbitrary numbers in a truly portable way. https://gibson042.github.io/canonicaljson-spec/ is such a specification.

**Comment by tupelo-schneck** [comment]
Do you consider it necessary for the JCS specification to specify how "333333333.33333328" is canonicalized, even though it has more precision than IEEE-754 double precision offers, and is (presumably) not something that would ever be output by software that serializes IEEE-754 double precision values?

If so, my strong recommendation is to just say ALL numbers must be canonicalized like ES6 `JSON.stringify(JSON.parse(input))` (with Note 2 compliance).  That should neatly deal with all questions of range and precision in a simple and uniform way.

**Comment by cyberphone** [comment]
JCS does not really specify how 333333333.33333328 is to be canonicalized, it rather specifies (through ES6) that 0x41b3de4355555554 should _serialized_ as 333333333.33333328.  What's clearly missing is specifying how input _parsing_ should deal with numbers that doesn't fit exactly precision-wise.  I will add that. Thanx!

However, changing JCS so that 1e+500 and 1e+400 would (standards-wise) be considered identical doesn't seem like a cool idea when there is a another scheme dealing with arbitrary precision and range in a platform independent way.

If you find 1e+500 expressed as a JSON Number in a JSON input stream, JCS is simply put not the right solution because such values are not (currently) useful with _native_ JavaScript anyway.  Using the quoted serialization mode such numbers are already used with JavaScript and would also pass JCS without issues.  BigIntegers are very common but they are usually coded in more efficient formats such as quoted Base64.

**Comment by tupelo-schneck** [comment]
I still suggest that the easiest  and best path is to say "numbers are parsed and re-serialized like ES6 with Note 2 compliance".  It seems like additional effort for a worse result to say "that, but, if the input would have parsed to Infinity, then the re-serialization is undefined".

IEEE-754 does include, after all, Infinity, so you should indicate how that value is serialized, and it is most consistent and easiest to specify that it serializes to JSON the way ES6 does.

It is even more effort to explain what happens to inputs like 1e-400.  ES6 parses it to 0.  Do you want to say that its behavior under JCS is undefined?

I would say that JCS can make 1e+500 and 1e+400 produce identical output, or it can make them both invalid input, or it can make the output undefined.  I am designing a system which involves signing JSON texts and I would like to use JCS.  Of those three options, the last (output is undefined) seems clearly bad, because it could create mostly invisible and potentially hard to debug interoperability problems.  The second (input is invalid) would be acceptable, I think.  But I like the first option (outputs are identical) the best and most consistent with the rest of the JCS specification.  It's true that two different inputs end up with identical signatures, but that's also true of 333333333.33333328 and 333333333.33333325, or 4e-324 and 5e-324, and so if JCS already does that this seems no worse.  Users can be told "inputs which would produce identical results under ES6 `JSON.parse` will produce identical outputs".

As you've said many times, users who really care about numbers of unusual precision and range will just use JSON strings.  Fine.  But I would prefer my system to behave reasonably and predictably when a user does, for whatever reason, produce JSON input which has a number like 333333333.33333328 or 4e-324 or 1e309.  I'm okay with it not preserving the full meaning.  Since you care about the canonicalization of 333333333.33333328 under JCS, but are willing to round, you must feel somewhat the same way.

**Comment by cyberphone** [comment]
The easiest is simply stating that a conforming JCS implementation SHOULD _reject_ numbers that doesn't fit the valid IEEE-754 _range_, while loss of _precision_ is (by design) ignored.

AFACT, "pathological" values like 1e-400 or 333333333.33333328 when dealt with by IEEE compatible parsing generate a consistent result.  _This is clearly also worth adding to the spec_.

**Comment by tupelo-schneck** [comment]
So do you reject 1e-400 or accept it as being parsed to a value of 0?  Do you consider that "range" or "precision"?

Values like 1e+400 also generate a consistent result when dealt with by IEEE (and ES6) compatible parsing: Infinity.  And that valid IEEE-754 value has a JSON serialization specified by ES6 which I would encourage you to just use, as being the most consistent with everything else JCS does.

But, if your proposal for JCS is to specify that "inputs including numbers which an IEEE-754 compatible parser will parse to Infinity or -Infinity SHOULD be rejected", I would consider that acceptable.

**Comment by cyberphone** [comment]
1e-400 is treated as 0 because this is how IEEE compatible number parsers deal with it.  If this is a range or precision issue is outside of JCS specification given the _revised_ text.

Yes, Infinity and -Infinity SHOULD be rejected, anything else would indicate that the application is doing something JCS wasn't designed for.

I hope that is ok...

**Comment by tupelo-schneck** [comment]
You find it reasonable that 1e-400 and 1e-500 should be allowed inputs that produce the same canonical serialization, but not 1e+400 and 1e+500.  I'm not convinced that the two cases should be considered so different.

That said, I see no need to strenuously object to the difference.  It is reasonable enough.

**Comment by cyberphone** [comment]
It is at least reasonable if one accept the limitations of IEEE-754 double precision arithmetic.

As I have mentioned there is another method which is "perfect".  Unfortunately perfection comes at a price which is why I haven't taken that route.  In particular, intermediaries rewriting JSON appear making life a bit harder than necessary.  An earlier effort of mine was [rightfully] shot down due to such considerations. 

Anyway, I will add clarifications along the lines we have discussed!
